champtc/opencti

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

Fixed VSAC Vulnerability Scans List Menu

---

opencti-platform/opencti-front/src/setupProxy.js

Added Secure: False to createProxyMiddleware

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

Fixed Explore results BTN

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

Task-4203: Configure ScatterPlot to render properly

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js
opencti-platform/opencti-front/src/services/api.service.js

Remove hard coded client id values

---

opencti-platform/opencti-graphql/src/cyio/schema/assets/asset-common/resolvers.js
opencti-platform/opencti-graphql/src/cyio/schema/assets/asset-common/sparql-query.js
opencti-platform/opencti-graphql/src/cyio/schema/assets/asset-common/typeDefs.graphql
opencti-platform/opencti-graphql/src/cyio/schema/assets/software/sparql-query.js

Applying mutators for delete single and multiple assets.
BIG NOTE!!!!!!
This required a merge from develop which resulted in merge conflicts due to changes made to my target source code. The behavior I tested showed working behavior as anticipated but may require more testing from @CyberDaedalus00

AB#4284 Asset Delete Mutators

---

opencti-platform/opencti-front/src/components/list_cards/CyioListCards.js
opencti-platform/opencti-front/src/components/list_lines/CyioListLines.js
opencti-platform/opencti-front/src/private/components/assets/Devices.js
opencti-platform/opencti-front/src/private/components/assets/Network.js
opencti-platform/opencti-front/src/private/components/assets/Software.js
opencti-platform/opencti-front/src/private/components/assets/devices/DeviceLine.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkLine.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareLine.js

bug 4265 fixed

---

opencti-platform/opencti-front/src/relay/environmentDarkLight.js

fixed hardcoded value

---

opencti-platform/opencti-front/src/relay/environmentDarkLight.js

Fixed Hard Coded value

---

opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetCreationOverview.js
opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetEditionOverview.js
opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectAssetOverview.js

bug 4270 fixed

---

opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkCreation.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkEditionContainer.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCreation.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareEditionContainer.js
opencti-platform/opencti-front/src/private/components/common/stix_domain_objects/CyioDomainObjectHeader.js

bug 4274 fixed

---

opencti-platform/opencti-front/src/private/components/assets/devices/DevicesLines.js

bug 4382 fixed

---

opencti-platform/opencti-front/src/private/components/nav/LeftBar.js
opencti-platform/opencti-front/src/private/components/nav/UserPreferencesModal.js

Fixed UserPrefModal Cancel Btn
*
*
*
*

Fixed LeftBar Org HardCoded Value

---

opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreationDetails.js
opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionDetails.js
opencti-platform/opencti-front/src/private/components/common/form/InstalledAsset.js

bug 4411 fixed

---

opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
opencti-platform/opencti-front/src/private/components/assets/devices/DeviceEditionContainer.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkCreation.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkEditionContainer.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCreation.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareEditionContainer.js

bug 4428 fixed

---

opencti-platform/opencti-front/src/private/components/nav/UserPreferencesModal.js

bug-4421: [USER PREFS] Three dots does nothing

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

The code use the upload_date for the Scan Date the report_date.

changed the use of upload_date to report_date as the value of Scan Date

---

opencti-platform/opencti-front/src/private/components/vsac/modals/VulnerabilityScan.js
opencti-platform/opencti-front/yarn.lock

Attempting a fix with the upload scan modal for drag-drop and file browse. Had issues with crhome where a reference was not being made in the react components therefor preventing us from getting the file name of the scan. Fixed this by getting the scan name directly from the dom event for the base input and extracting the file name form the path value.
@ddavisDarkLight you will want to merge this when you can.

AB#4431 Fixing file reference/name for scan upload modal

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js
opencti-platform/opencti-front/src/private/components/vsac/modals/NewAnalysis.js

Fixed the bug for Cancel button in New Analysis

---

opencti-platform/opencti-front/src/private/components/vsac/ExploreResults.js

bug-4430: In Explore Details, the Host Info box is not being populated

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

Fixed axis labels, numeric labels and bubbles in ScatterChart

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

Secutree vsac 4548 bugfix

---

opencti-platform/opencti-front/src/private/components/vsac/modals/GenerateReport.js

Fixed the overlayed button in GenerateReport

---

opencti-platform/opencti-front/src/private/components/vsac/ViewCharts.js

Fixed size of bubbles, color of labels and overlap text in ViewCharts

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

Fixed instance of menu opening

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js

Fixed the update error in VulnerabilityScan

---

opencti-platform/opencti-front/src/private/components/vsac/ExploreResults.js
opencti-platform/opencti-front/src/private/components/vsac/components/Hosts.js
opencti-platform/opencti-front/src/private/components/vsac/components/Products.js
opencti-platform/opencti-front/src/private/components/vsac/components/VulnerabilityAccordionCards.js
opencti-platform/opencti-front/src/private/components/vsac/components/WeaknessAccordionCards.js

Secutree vsac 4553 task

---

opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCard.js
opencti-platform/opencti-front/src/private/components/assets/devices/DeviceLine.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkCard.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkLine.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCard.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareLine.js

Fixed the highlighting color of asset fields

---

opencti-platform/opencti-front/src/private/components/assets/devices/DeviceCreation.js
opencti-platform/opencti-front/src/private/components/assets/network/NetworkCreation.js
opencti-platform/opencti-front/src/private/components/assets/software/SoftwareCreation.js

Secutree all 4588 bugfix

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js
opencti-platform/opencti-front/src/private/components/vsac/ViewCharts.js
opencti-platform/opencti-front/src/resources/css/index.css

Fixes View Chart crash
*
*
*
*

Fixes AB#4429

---

opencti-platform/opencti-front/src/private/components/vsac/Scans.js
opencti-platform/opencti-front/src/private/components/vsac/modals/NewAnalysis.js
opencti-platform/opencti-front/src/services/analysis.service.js

New Analysis modal will no longer give the option of scans to select but rather display the scan for the analysis. The modal will now validate that the user has selected an option for each field before enabling the submit button. The scan name display will show a skeleton until the scan is retrieved.

AB#4549 Enhancements to the New Analysis modal

---

opencti-platform/opencti-front/src/private/components/vsac/Compare.js

Fixed Legend panel issue on scroll in Compare component

---

opencti-platform/opencti-graphql/src/http/httpPlatform.js

fix: adding freshdesk to script-src value for security content policy on the server. Attempting to fix rendering issues

AB#4650 Rnd 2

---

opencti-platform/opencti-front/src/private/components/nav/LeftBar.js

AB#4672 - Remove Navigation Links to Broken/Empty/Improver pages
